questionlist =[
'Abstract data type (ADT) ',
'Abstraction ',
'Acceptance testing ',
'Accepting State',
'Access rights (data security) ',
'Access rights (database) ',
'Accumulator',
'Accumulator ',
'Acknowledgement ',
'ACM ',
'Adaptive maintenance ',
'Address bus ',
'Addressing modes ',
'Wi-FI',
'Algorithm ',
'Alpha testing ',
'Analogue to digital converter (ADC) ',
'Analysis ',
'Antivirus software ',
'Append ',
'Argument ',
'Arithmetic Logic Unit',
'Arithmetic shift ',
'ARPAnet ',
'Array ',
'Artificial intelligence (AI) ',
'Artificial neural networks ',
'ASCII code ',
'Assembler ',
'Assembly language ',
'Asymmetric encryption ',
'Asynchronous serial data transmission ',
'Attenuation',
'Attribute',
'Attribute',
'Attribute (database) ',
'Attributes (class) ',
'Audio compression ',
'Authentication',
'Authentication ',
'Automatic Repeat Request (ARQ)',
'Back propagation ',
'Back up utility',
'Backus Naur form (BNF) notation ',
'Bad sector ',
'Base case ',
'BCD',
'BCS ',
'Beladys anomaly ',
'Beta testing ',
'Bidirectional ',
'Binary',
'Binary file ',
'Binary floating point number',
'Binary search ',
'Binary tree ',
'Binder 3D printing ',
'Biometrics ',
'Bit ',
'Bit depth ',
'Bit rate ',
'Bit size ',
'Bit streaming ',
'Bitmap (BMP)',
'BitTorrent ',
'Black box testing',
'Block chaining ',
'Block cipher ',
'Bluetooth ',
'Boolean',
'Boolean algebra ',
'Bootstrap ',
'Boundary test data ',
'Breakp oint ',
'Bridge ',
'Broadcast ',
'buffer',
'Burst time ',
'Bus network topology ',
'By reference ',
'By value ',
'Byte',
'Candidate Key',
'Channels ',
'Character set ',
'Chatbot ',
'Check digit ',
'Checksum',
'Checksum ',
'CIDR',
'Ciphertext ',
'Circuit Switching',
'CISC',
'Class',
'Class variable ',
'Classless inter-domain routing (CIDR)',
'CLI ',
'Client side scripting ',
'Clock cycle ',
'Close ',
'Cloud storage ',
'Cluster ',
'CMOS ',
'Coaxial cable',
'Code of conduct',
'Coding ',
'Collision ',
'Colour depth ',
'Combination circuit ',
'Compiler ',
'Composite data type ',
'Composite key ',
'computer ethics',
'Conflict ',
'Constant ',
'Constructor ',
'Constructor ',
'Containment (aggregation) ',
'Context switching ',
'Contiguous ',
'Control ',
'Control Bus',
'Control unit ',
'copyright',
'Core ',
'Corrective main tenance ',
'CPU',
'CSMA/ CD ',
'CSS',
'Culture ',
'Current instruction register (CIR) ',
'Cyclic shift ',
'Data',
'Data Bus',
'Data definition language (DDL) ',
'Data Dictionary',
'Data hiding ',
'Data Integrity',
'Data Management',
'Data manipulation language (DML) ',
'Data modelling',
'Data privacy ',
'Data protection laws ',
'Data redundancy ',
'Data Security',
'Data type ',
'Database ',
'Database management system (DBMS) ',
]
