import random
questionlist = ['Absolute addressing'
'Abstract data type (ADT) ',
'Abnormal test data ',
'Abstraction ',
'Acceptance testing ',
'Accepting State',
'Access rights (data security)',
'Access rights (database) ',
'Accumulator',
'Accumulator ',
'Acknowledgement ',
'ACM ',
'Adaptive maintenance ',
'Address bus ',
'Addressing modes ',
'Wi-FI',
'Algorithm ',
'Alpha testing ',
'Analogue to digital converter (ADC) ',
'Analysis ',
'Antivirus software ',
'Append ',
'Argument ',
'Arithmetic Logic Unit',
'Arithmetic shift ',
'ARPAnet ',
'Array ',
'Artificial intelligence (AI) ',
'Artificial neural networks ',
'ASCII code ',
'Assembler ',
'Assembly language ',
'Asymmetric encryption ',
'Asynchronous serial data transmission ',
'Attenuation',
'Attribute',
'Attribute',
'Attribute (database) ',
'Attributes (class) ',
'Audio compression ',
'Authentication',
'Authentication ',
'Automatic Repeat Request (ARQ)',
'Back propagation ',
'Back up utility',
'Backus Naur form (BNF) notation ',
'Bad sector ',
'Base case ',
'BCD',
'BCS ',
'Beladys anomaly',
'Beta testing ',
'Bidirectional ',
'Binary',
'Binary file ',
'Binary floating point number',
'Binary search ',
'Binary tree ',
'Binder 3D printing ',
'Biometrics ',
'Bit ',
'Bit depth ',
'Bit rate ',
'Bit size ',
'Bit streaming ',
'Bitmap (BMP)',
'BitTorrent ',
'Black box testing',
'Block chaining ',
'Block cipher ',
'Bluetooth ',
'Boolean',
'Boolean algebra ',
'Bootstrap ',
'Boundary test data ',
'Breakp oint ',
'Bridge ',
'Broadcast ',
'buffer',
'Burst time ',
'Bus network topology ',
'By reference ',
'By value ',
'Byte',
'Candidate Key',
'Channels ',
'Character set ',
'Chatbot ',
'Check digit ',
'Checksum',
'Checksum ',
'CIDR',
'Ciphertext ',
'Circuit Switching',
'CISC',
'Class',
'Class variable ',
'Classless inter-domain routing (CIDR)',
'CLI ',
'Client side scripting ',
'Clock cycle ',
'Close ',
'Cloud storage ',
'Cluster ',
'CMOS ',
'Coaxial cable',
'Code of conduct',
'Coding ',
'Collision ',
'Colour depth ',
'Combination circuit ',
'Compiler ',
'Composite data type ',
'Composite key ',
'computer ethics',
'Conflict ',
'Constant ',
'Constructor ',
'Constructor ',
'Containment (aggregation) ',
'Context switching ',
'Contiguous ',
'Control ',
'Control Bus',
'Control unit ',
'copyright',
'Core ',
'Corrective main tenance ',
'CPU',
'CSMA/ CD ',
'CSS',
'Culture ',
'Current instruction register (CIR) ',
'Cyclic shift ',
'Data',
'Data Bus',
'Data definition language (DDL) ',
'Data Dictionary',
'Data hiding ',
'Data Integrity',
'Data Management',
'Data manipulation language (DML) ',
'Data modelling',
'Data privacy ',
'Data protection laws ',
'Data redundancy ',
'Data Security',
'Data type ',
'Database ',
'Database management system (DBMS) ',
'DDL - Data Description Language',
'De Morgans law',
'Debugging ',
'Declarative programming ',
'Decomposition ',
'Deep learning ',
'Defragmentation',
'Denary',
'Design ',
'Destructor ',
'Developer interface ',
'Device driver ',
'Device Drivers',
'Dictionary',]
answerlist =[
    'testdata that should be rejected by a program.',
    'mode of addressing in which the contents of the memory location in the operand are used.',
    'a collection of data and a set of operations on that data.',
    'the process of extracting information that is essential, while ignoring what is not relevant, for the provision of a solution.',
    'the testing of a completed program to prove to the customer that it works as required.',
    'A state the system reaches when the input string is valid',
    'use of access levels to ensure only authorised users can gain access to certain data.',
    'the permissions given to database users to access, modify or delete data.',
    'A general purpose register that stores a balue before and after the exectution of an instruction by the ALU',
    'temporary general purpose register which stores numerical values at any part of a given operation.',
    'message sent to a receiver to indicate that data has been received without error.',
    'Association for Computing Machinery.',
    'the alteration of a program to perform new tasks.',
    'carries the addresses throughout the computer system.',
    'different methods of using the operand part of a machine code instruction as a memory address.',
    'wireless connect ivity that uses radio waves & microwaves.',
    'an ordered set of steps to be followed in the completion of a task.',
    'the testing of a completed or nearly completed program in-house by the development team',
    'needed to convert analogue data (read from sensors, for example) into a form understood by a computer.',
    'part of the program development lifecycle; a process of investigation, leading to the specification of what a program is required to do.',
    'software that quarantines and deletes files or programs infected by a virus (or other malware); it can be run in the background or initiated by the user.',
    'file access mode in which data can be added to the end of a file.',
    'the value passed to a procedure or function.',
    'logic unit (ALU) ',
    'the sign of the number is preserved.',
    'Advanced Research Projects Agency Network.',
    'a data structure containing several elements of the same data type.',
    'machine or application which carries out a task that requires some degree of intelligence when carried out by a human counterpart.',
    'networks of interconnected nodes based on the interconnections between neurons in the human brain; the system is able to think like a human using these neural networks, and its performance improves with more data.',
    'coding system for all the characters on a keyboard and control codes.',
    'a computer program that translates programming code written in assembly language into machine code; assemblers can be one pass or two pass.',
    'a low',
    'encryption that uses public keys (known to everyone) and private keys (secret keys).',
    'serial refers to a single wire being used to transmit bits of data one after the other; asynchronous refers to a sender using its own clock/ timer device rather sharing the same clock/timer with the recipient device.',
    'deterioration of signal',
    'In database management systems, the term attribute is sometimes used as a synonym for field.',
    'a named piece of data stored within an object',
    'an individual data item stored for an entity; for example, for a person, attributes could include name, address, date of birth.',
    'the data items in a class.',
    'method used to reduce the size of a sound file using perceptual music shaping.',
    'The origin of the message can be verified.',
    'a way of proving somebody or something is who or what they claim to be.',
    'A method of data verification. A sends information to B. A keeps copy of message and B sends the message back when it has received it. If A doesnt hear from B then A sends it again after a reasonable amount of time.',
    'method used in artificial neural networks to calculate error gradients so that actual node/neuron weightings can be adjusted to improve the performance of the model.',
    'software that makes copies of files on another portable storage device.',
    'a formal method of defining the grammatical rules of a programming language.',
    'a faulty sector on an HOD which can be soft or hard.',
    'a terminating solution to a process that is not recursive.',
    'BInary Coded Decimal',
    'British Computer Society.',
    'phenomenon which means it is possible to have more page faults when increasing the number of page frames.',
    'the testing of a completed program by a small group of users before it is released.',
    'used to describe a bus in which bits can travel in both directions.',
    'Numbers that consist of the digits 0 and 1.',
    'a file that does not contain text only; the file is machine',
    'a binary number written in the form M x 2E (where M is the mantissa and E is the exponent).',
    'a method of searching an ordered list by testing the value of t he middle item in the list and rejecting the half .of the list that does not contain the required value.',
    'A hierarchical data structure in which each parent node can have a maximum of two child nodes',
    '3D printing method that uses a two-stage pass; the first stage uses dry powder and the second stage uses a binding agent',
    'use of unique human characteristics to identify a  user (such as fingerprints or face recognition',
    'abbreviation for binary digit.',
    'number of bits used to represent the smallest unit in, for example, a sound or image file; the larger the bit depth, the better the quality of the sound or colour image.',
    'number of bits per second that can be transmitted over a network; it is a measure of the data transfer rate over a digital telecoms network..',
    'Determines how much information can be stored in a file',
    'contiguous sequence of digital bits sent over a network/internet.',
    'A bitmap image is made up of a grid of rows and columns where a specific cell is given a colour value. ',
    'protocol used in peer',
    'a method of testing a program that tests a modules inputs and outputs. Called black box because no access to source code.',
    'form of encryption, in which the previous block of ciphertext is X0Red with the block of plaintext and then encrypted thus preventing identical plaintext blocks producing identical ciphert ext.',
    'the encryption of a number of contiguous bits in one go rather than one bit at a time.',
    'wireless connectivity that uses radio waves in the 2.45 GHz frequency band.',
    'A data type that only has two values, true or false',
    'a form of algebra linked to logic circuits and based on TRUE and FALSE.',
    'a small program that is used to load other programs to start up a computer.',
    'test data that is on the limit of that accepted by a program or data that is just outside the limit of that rejected by a program.',
    'a deliberate pause in the execution of a program during testing so that the contents of variables, registers, and so on can be inspected to aid debugging.',
    'device that connects LANs which use the same protocols.',
    'communication where pieces of data are sent from sender to receiver.',
    'Where information loaded from the internet is temporarily stored in this cache, so that a slow connection doesnt cause buffering of data, commonly used for videos ',
    'the time when a process has control of the CPU .',
    'network using single central cable in which all devices are connected to this cable; data can only travel in one direction and only one device is allowed to transmit at a time.',
    'a method of passing a parameter to a procedure in which the value of the variable can be changed by the procedure.',
    'a method of passing a parameter to a procedure in which the value of the variable cannot be changed by the procedure.',
    'A group of eight bits treated as a single unit ',
    'A Candidate Key can be any column or a combination of columns that can qualify as unique key indatabase. There can be multiple Candidate Keys in one table. Each Candidate Key can qualify as Primary Key. Primary Key – A Primary Key is a column or a combination of columns that uniquely identify a record.',
    'Channels are the number of separate recording elements in the data',
    'a list of characters that have been defined by computer hardware and software; it is necessary to have a method of coding, so that the computer can understand human characters',
    'computer program set up to simulate conversational interaction between humans and a website.',
    'additional digit appended to a number to check if entered data is error',
    'The transmitting end defines a block as a number of bytes. The sum of the binary numbers in a block is calculated and supplied as a checksum value during transmission, this is repeated for each block. The receiver does the same  and checks its value with the checksum value transmitted for each block.',
    'verification method used to check if data transferred has been altered or corrupted; calculated from the block of data to be sent.',
    'Classless Inter-Domain Routing, sometimes called supernetting is a way to allow more flexible allocation of Internet Protocol (IP) addresses than was possible with the original system of IP address classes. ',
    'the product when plain text is put through an encryption algorithm .',
    'This is where two computers establish a dedicated channel for communication',
    'Complex instruction set computer refers to computers designed with a full set of computer instructions that were intended to provide needed capabilities in the most efficient way',
    'a template defining the methods and data of a certain type of object.',
    'a single copy of this data exists across all objects of a class',
    'increases IPv4 flexibility by adding a suffix to the IP address, such as 200.21.100.6/18.',
    'command line interface.',
    'When the code for the web page is proccessed on the users machine itself ',
    'clock speeds are measured in terms of GHz; this is the vibra t io nal frequ ency of the clock which sends out pulses along the control bus; a 3.5 GHZ clock cycle means 3.5 billion clock cycles a second.',
    'file-processing operation; closes a file so it can no longer be used by a program.',
    'method of data storage where data is stored on off-site server ',
    'a number of computers (containing SIMD processors) networked together.',
    'complementary metal-oxide semiconductor.',
    'Cable made up of central copper core, insulation, copper mesh and outer insulation',
    'a set of rules governing the behaviour of a group or organisation (e.g. computer professionals)',
    'part of the program development lifecycle; the writing of the program or suite of programs.',
    'situation in which two messages/data from different sources are trying to transmit along the same data channel.',
    'number of bits used to represent the colours in a pixel, e.g. 8 bit colour depth can represent 2^8 = 256 Colours.',
    'circuit in which the output depends entirely on the input values.',
    'a computer program that translates a source program written in a high level language to machine code or p-code, object code.',
    'a data type constructed using several of the basic data types available in a particular programming language.',
    'a set of attributes that form a primary key to provide a unique identifier for a table.',
    'moral principles governing the design, building, implementation and use of computer systems',
    'situation in which two devices have the same IP address.',
    'a named value that cannot change during the execution of a program.',
    'a method used to initialise a new object.',
    'a special method to tell Python how to create an object of this class: in Python, the constructor method is always called __init__ with a double underscore on each side of ‘init’',
    'process by which one class can contain other classes.',
    'procedure by which, when the next process takes control of the CPU, its previous state is reinstated or restored.',
    'items next to each other.',
    'to automatically take readings from a device, then use the data from those readings to adjust the device.',
    'A bidirectional bus which transmits a signal from the control unit to any other system compenent',
    'ensures synchronisation of data flow and programs throughout the computer by sending out control signals along the control bus.',
    'the legal right to intellectual property',
    'a unit made up of ALU, control unit and registers which is part of a CPU; a CPU may contain a number of cores.',
    'the correction of any errors that appear during use.',
    'Central proccessing unit -  Process all the instructions in the computer by doing basic arithmethics ',
    'carrier sense multiple access with collision detection; a method used to detect collisions and resolve the issue.',
    'Cascading Style Sheets. Used to stylize websites.',
    'the attitudes, values and practices shared by a group of people/society.',
    'this is a register used to contain the instruction which is currently being executed or decoded.',
    'no bits are lost; bits shifted out of one end of the register are introduced at the other end of the register.',
    'The individual samples. An individual sample is the bit size times the number of channels. ',
    'A component that carries data to and from the proccesor allows data to be carried from processor to memory (and vice versa) or to and from input/output devices',
    'a language used to create, modify and remove the data structures that form a database.',
    'A data dictionary is a collection of descriptions of the data objects or items in adata model for the benefit of programmers and others who need to refer to them. A first step in analyzing a system of objects with which users interact is to identify each object and its relationship to other objects.',
    'technique which protects the integrity of an object by restricting access to the data and methods within that object',
    'Data integrity refers to maintaining and assuring the accuracy and consistency of data over its entire life-cycle, and is a critical aspect to the design, implementation and usage of any system which stores, processes, or retrieves data.',
    'Data management is the process of controlling the information generated during a research project. Any research will require some level of data management, and funding agencies are increasingly requiring scholars to plan and execute good data managementpractices.',
    'a language used to add, modify, delete and retrieve the data stored in a relational database.',
    'Data modeling is often the first step in database design and object-oriented programming as the designers first create a conceptual model of how data items relate to each other. Data modeling involves a progression from conceptual model to logical model to physical schema.',
    'the privacy of personal information, or other information stored on a computer, that should not be accessed by unauthorised parties.',
    'laws which govern how data should be kept private and secure.',
    'situation in which the same data is stored on several servers in case of maintenance or repair.',
    'Data security means protecting data, such as a database, from destructive forces and from the unwanted actions of unauthorized users.',
    'a classification attributed to an item of data, which determines the types of value it can take and how it can be used.',
    'a structured collection of items of data that can be accessed by different applications programs.',
    'systems software for the definition, creation and manipulation of a database.',
    'A language used to describe the data in a database',
    'A transformation rule that are both valid rules of inference',
    'the process of finding logic errors in a computer program by running or tracing the program.',
    'statements of facts and rules together with a mechanism for setting goals in the form of a query.',
    'the process of breaking a complex problem into smaller parts.',
    'machines that think in a way similar to the human brain; they handle huge amounts of data using artificial neural networks.',
    'Reduce the fragmentation of (a file) by concatenating parts stored in separate locations on a disk.',
    'The numbers we use in everyday life: digits between 0-9.',
    'part of the program development lifecycle; it uses the program specification from the analysis stage to show how the program should be developed .',
    'a method that is automatically invoked when an object is destroyed.',
    'feature of a DBMS that provides developers with the commands required for definition, creation and manipulation of a database.',
    'software that communicates with the operating system and translates data into a format understood by the device.',
    'A device driver is a program that controls a particular type of device that is attached to your computer. ',
    'an abstract data type that consists of pairs, a key and a value, in which the key is used to find the value.',
    ]

